config/routes.rb
Rails.application.routes.draw do
  get 'users/profile'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }
  resources :posts
  get 'test/index'
  root 'pages#home'
  get 'about', to: 'pages#about'
  get '/profuser/:id', to: 'users#profile', as: 'user'
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <%= link_to 'Rails Blog', root_path, class: "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Blog', posts_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to 'About', about_path, class: "nav-link"%>
        </li>

      </ul>

      <ul class="navbar-nav">
        <%= render 'layouts/user_session_manager' %>
      </ul>


    </div>
  </div>
</nav>

app/views/layouts/_user_session_manager.html.erb
<ul class="navbar-nav">
  <% if current_user %>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        <%= current_user.name%>
      </a>
      <ul class="dropdown-menu dropdown-menu-lg-end" aria-labelledby="navbarDropdown">
        <li><%= link_to 'New Post', new_post_path, class:"dropdown-item"%></li>
        <li><a class="dropdown-item" href="#">Action</a></li>
        <li><%= link_to 'Edit Account', edit_user_registration_path, class:"dropdown-item"%></li>
        <li><hr class="dropdown-divider"></li>
        <li>
          <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class:"dropdown-item" %>
        </li>
      </ul>
    </li>
  <% else %>
    <li class="nav-item">
      <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link"%>
    </li>
    <li class="nav-item">
      <%= link_to 'Sign In',new_user_session_path, class: "nav-link"%>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <%= render 'layouts/nav' %>
      <br>
    </header>
    <main class="container my-4">
      <% if notice %>
        <p class="notice"><%= notice %></p>

      <% elsif alert %>
        <p class="alert"><%= alert %></p>
      <%end %>

      <%= yield %>
    </main>
  </body>
</html>